version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: diploma_postgres
    environment:
      POSTGRES_USER: cinema
      POSTGRES_PASSWORD: cinema
      POSTGRES_DB: cinema
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./postgres/init:/docker-entrypoint-initdb.d
    ports:
      - "15432:5432"

volumes:
  pgdata:
